language: php

php:
  - 5.6
  - 7.0

branches:
  only:
    - master
    - develop

before_script:
  - cp .env.travis .env
  - mysql -e 'create database legendsrising_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit